<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6vn3vUM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6vn3vUM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6vn3vUM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6vn3vUM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6vn3vUM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6vn3vUM',
    'container.build_id' => 'daa682e0',
    'container.build_time' => 1603403842,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6vn3vUM');
